export const FETCH_USER_PROFILE_START = 'FETCH_USER_PROFILE_START';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
// ACHIEVEMENTS
export const FETCH_ACHIEVEMENTS_START = 'FETCH_ACHIEVEMENTS_START';
export const FETCH_ACHIEVEMENTS_SUCCESS = 'FETCH_ACHIEVEMENTS_SUCCESS';
export const FETCH_ACHIEVEMENTS_SHORT_START = 'FETCH_ACHIEVEMENTS_SHORT_START';
export const FETCH_ACHIEVEMENTS_SHORT_SUCCESS = 'FETCH_ACHIEVEMENTS_SHORT_SUCCESS';
export const FETCH_SPECIAL_ACHIEVEMENTS_START = 'FETCH_SPECIAL_ACHIEVEMENTS_START';
export const FETCH_SPECIAL_ACHIEVEMENTS_SUCCESS = 'FETCH_SPECIAL_ACHIEVEMENTS_SUCCESS';
export const FETCH_SPECIAL_ACHIEVEMENTS_FAILURE = 'FETCH_SPECIAL_ACHIEVEMENTS_FAILURE';
export const LOAD_ACHIEVEMENTS_SUCCESS = 'LOAD_ACHIEVEMENTS_SUCCESS';
export const FILTER_USER_ACHIEVEMENTS = 'FILTER_USER_ACHIEVEMENTS';
// SETTINGS
export const SETTINGS_SCREEN_TOGGLE = 'SETTINGS_SCREEN_TOGGLE';
export const SETTINGS_LOCK_TOGGLE = 'SETTINGS_LOCK_TOGGLE';
export const SETTINGS_HELPERS_TOGGLE = 'SETTINGS_HELPERS_TOGGLE';
export const SETTINGS_NICKNAME_LENGTH_SET = 'SETTINGS_NICKNAME_LENGTH_SET';
// GAMES
export const FETCH_USER_GAMES_SHORT_SUCCESS = 'FETCH_USER_GAMES_SHORT_SUCCESS';
export const FETCH_USER_GAMES_SHORT_START = 'FETCH_USER_GAMES_SHORT_START';
export const FETCH_GAME_PREVIEW_START = 'FETCH_GAME_PREVIEW_START';
export const FETCH_GAME_PREVIEW_SUCCESS = 'FETCH_GAME_PREVIEW_SUCCESS';
export const FETCH_USER_GAMES_START = 'FETCH_USER_GAMES_START';
export const FETCH_USER_GAMES_SUCCESS = 'FETCH_USER_GAMES_SUCCESS';
// export const GAME_UNMOUNT = 'GAME_UNMOUNT';
export const FETCH_GAME_PLAY_START = 'FETCH_GAME_PLAY_START';
export const FETCH_GAME_PLAY_SUCCESS = 'FETCH_GAME_PLAY_SUCCESS';
// GAME INSIDE
export const FETCH_GAME_CATEGORIES_START = 'FETCH_GAME_CATEGORY_START';
export const FETCH_GAME_CATEGORIES_SUCCESS = 'FETCH_GAME_CATEGORY_SUCCESS';
export const CHOOSE_GAME_CATEGORY = 'CHOOSE_GAME_CATEGORY';
