export const FETCH_USER_PROFILE_START = 'FETCH_USER_PROFILE_START';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_LAST_TEACHER_GAME_START = 'FETCH_LAST_TEACHER_GAME_START';
export const FETCH_LAST_TEACHER_GAME_SUCCESS = 'FETCH_LAST_TEACHER_GAME_SUCCESS';
// ACHIEVEMENTS
export const FETCH_ACHIEVEMENTS_START = 'FETCH_ACHIEVEMENTS_START';
export const FETCH_ACHIEVEMENTS_SUCCESS = 'FETCH_ACHIEVEMENTS_SUCCESS';
export const FETCH_ACHIEVEMENTS_SHORT_START = 'FETCH_ACHIEVEMENTS_SHORT_START';
export const FETCH_ACHIEVEMENTS_SHORT_SUCCESS = 'FETCH_ACHIEVEMENTS_SHORT_SUCCESS';
export const FETCH_SPECIAL_ACHIEVEMENTS_START = 'FETCH_SPECIAL_ACHIEVEMENTS_START';
export const FETCH_SPECIAL_ACHIEVEMENTS_SUCCESS = 'FETCH_SPECIAL_ACHIEVEMENTS_SUCCESS';
export const FETCH_SPECIAL_ACHIEVEMENTS_FAILURE = 'FETCH_SPECIAL_ACHIEVEMENTS_FAILURE';
export const LOAD_ACHIEVEMENTS_SUCCESS = 'LOAD_ACHIEVEMENTS_SUCCESS';
export const FILTER_USER_ACHIEVEMENTS = 'FILTER_USER_ACHIEVEMENTS';
// SETTINGS
export const SETTINGS_SCREEN_TOGGLE = 'SETTINGS_SCREEN_TOGGLE';
export const SETTINGS_LOCK_TOGGLE = 'SETTINGS_LOCK_TOGGLE';
export const SETTINGS_HELPERS_TOGGLE = 'SETTINGS_HELPERS_TOGGLE';
export const SETTINGS_NICKNAME_LENGTH_SET = 'SETTINGS_NICKNAME_LENGTH_SET';
// GAMES
export const FETCH_USER_GAMES_SHORT_SUCCESS = 'FETCH_USER_GAMES_SHORT_SUCCESS';
export const FETCH_USER_GAMES_SHORT_START = 'FETCH_USER_GAMES_SHORT_START';
export const FETCH_TEACHER_GAMES_SHORT_SUCCESS = 'FETCH_TEACHER_GAMES_SHORT_SUCCESS';
export const FETCH_TEACHER_GAMES_SHORT_START = 'FETCH_TEACHER_GAMES_SHORT_START';
export const FETCH_GAME_PREVIEW_START = 'FETCH_GAME_PREVIEW_START';
export const FETCH_GAME_PREVIEW_SUCCESS = 'FETCH_GAME_PREVIEW_SUCCESS';
export const FETCH_USER_GAMES_START = 'FETCH_USER_GAMES_START';
export const FETCH_USER_GAMES_SUCCESS = 'FETCH_USER_GAMES_SUCCESS';
export const FETCH_GAME_PLAY_START = 'FETCH_GAME_PLAY_START';
export const FETCH_GAME_PLAY_SUCCESS = 'FETCH_GAME_PLAY_SUCCESS';
// GAME INSIDE
export const ANIMATE_GAME_CATEGORIES = 'FETCH_GAME_CATEGORY';
export const ANIMATE_GAME_CATEGORIES_END = 'FETCH_GAME_CATEGORY_END';
export const CHOOSE_GAME_CATEGORY = 'CHOOSE_GAME_CATEGORY';
export const TOGGLE_CATEGORIES_VISIBILITY = 'TOGGLE_CATEGORIES_VISIBILITY';
export const PASS_CATEGORY = 'PASS_CATEGORY';
export const SEND_NEXT_QUESTION = 'SEND_NEXT_QUESTION';
export const THROW_ANSWER_OPTION = 'THROW_ANSWER_OPTION';
export const REMOVE_ANSWER_OPTION = 'REMOVE_ANSWER_OPTION';
export const SET_ANSWER_POSSIBILITY = 'SET_ANSWER_POSSIBILITY';
export const SET_REPLACE_POSSIBILITY = 'SET_REPLACE_POSSIBILITY';
export const SET_OPTION_FOCUSED = 'SET_OPTION_FOCUSED';
export const REPLACE_ANSWER_OPTION = 'REPLACE_ANSWER_OPTION';
export const PASS_ANSWER_FOR_THE_QUESTION = 'PASS_ANSWER_FOR_THE_QUESTION';
export const END_THE_GAME = 'END_THE_GAME';
